[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5" # Look here if issues with Axum.... this differs from tut.
tokio = { version = "1", features = ["full"] }